config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
      resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"
    get "/customers/edit" => "customers#edit", as: "edit"
    resources :customers, only: [:update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/orders/confirm" => "orders#confirm"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, presence: true
  validates :address, :name, presence: true

	# 配送先住所情報の結合
	def address_display
	    self.postal_code + " " + self.address + " " + self.name
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  # 会員フルネーム カナ
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted === false)
  end

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  scope :active, -> {where(is_active: true)}

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  attachment :image
  validates :is_active, inclusion: { in: [true, false] }

  scope :active, -> {where(is_active: true)}

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  # 注文モデル
  enum payment: { credit_card: 0, transfer: 1 }

  # enumで管理, {0: 入金待ち, 1: 入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み}
  enum status: { wating: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  # enumuで管理, {0: 着手不可, 1:製作待ち, 2: 製作中, 3: 制作完了}
  enum making_status: { no_making: 0, wating: 1, making: 2, finished: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  # このcontrollerを記述する　3/3 private paramsが必要　indexも確認
  def index
    @customers = Customer.page(params[:page])
    @customer = Customer.new
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)

  end

  private
	def order_params
		params.require(:order).permit(:status, )
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)

    if @order.status == "paid_up"
      @order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div　class="row">
  <h4><%= @customer.full_name %>さんの会員情報編集</h4>
  <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, local: true do |f| %>
    <table class="table">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th><%= f.label :name, "氏名" %></th>
        <td><%= f.text_field :last_name %>
            <%= f.text_field :first_name %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :name, "フリガナ" %></th>
        <td>
          <%= f.text_field :last_name_kana %>
          <%= f.text_field :first_name_kana %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :postal_code, "郵便番号" %></th>
        <td><%= f.number_field :postal_code %></td>
      </tr>
      <tr>
        <th><%= f.label :address, "住所" %></th>
        <td><%= f.text_field :address %></td>
      </tr>
      <tr>
        <th><%= f.label :telephone_number, "電話番号(ハイフンなし)" %></th>
        <td><%= f.telephone_field :telephone_number %></td>
      </tr>
      <tr>
        <th><%= f.label :email, "メールアドレス" %></th>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <th><%= f.label :is_deleted, "会員ステータス" %></th>
        <td>
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効", value: :false %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会", value: :true %>
        </td>
      </tr>
      <tr>
        <th></th>
        <td class="row text-right">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <h2>会員一覧</h2>
    <table class="table table-bordered">
      <thead>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <% if customer.is_deleted == false %>
              <td>有効</td>
            <% else %>
              <td>退会</td>
            <% end %>
          </tr>
        <% end %>
        <%= paginate @customers %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="row">
  <div class="col-xs-offset-1">
    <h4><%= @customer.full_name %>さんの会員詳細</h4>
    <br>

    <table class="table">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @customer.is_deleted == false %>
            有効
          <% else %>
            退会
          <% end %>
        </td>
      </tr>
    </table>
    <div>
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_order_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>