config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
      resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"
    get "/customers/edit" => "customers#edit", as: "edit"
    resources :customers, only: [:update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/orders/confirm" => "orders#confirm"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, presence: true
  validates :address, :name, presence: true

	# 配送先住所情報の結合
	def address_display
	    self.postal_code + " " + self.address + " " + self.name
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  # 会員フルネーム カナ
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted === false)
  end

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  scope :active, -> {where(is_active: true)}

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  attachment :image
  validates :is_active, inclusion: { in: [true, false] }

  scope :active, -> {where(is_active: true)}

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  # 注文モデル
  enum payment: { credit_card: 0, transfer: 1 }

  # enumで管理, {0: 入金待ち, 1: 入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み}
  enum status: { wating: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  # enumuで管理, {0: 着手不可, 1:製作待ち, 2: 製作中, 3: 制作完了}
  enum making_status: { no_making: 0, wating: 1, making: 2, finished: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)

  end

  private
	def order_params
		params.require(:order).permit(:status, )
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)

    if @order.status == "paid_up"
      @order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
    <h2>ジャンル編集</h2><br>
      <div class="edit-genre-form">
        <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
          <div>
            <%= f.label :name, "ジャンル名" %>
            <%= f.text_field :name, class:"genre_name", class: "col-md-4" %>
            <%= f.submit '変更を保存', class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
    <h2>ジャンル追加・一覧画面</h2><br>
      <div class="form-group col-md-10">
        <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
          <div>
            <%= f.label :name, "ジャンル名", class: "col-md-6" %>
            <%= f.text_field :name, class:"genre_name" %>
            <%= f.submit '新規登録', class:"btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <br>
      <table class="table genre-index">
        <thead>
          <tr>
            <th>ジャンル</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="row">
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
      <div class="col-xs-5">
      <h2>商品編集</h2>

      <div class="col-xs-5 col-xs-offset-2">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th><%= f.label :image, "商品画像" %></th>
              <td><%= f.file_field :image, accept: "image/*", class:"item_image" %></td>
            </tr>
            <tr>
              <th>商品名</th>
              <td><%= f.text_field :name, class: "form-control" %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= f.text_area :introduction, class: "form-control" %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
            </tr>
            <tr>
              <th>税抜価格</th>
              <td><%= f.text_field :price %>円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active_true, "販売中", value: :ture %>
                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active_false, "販売停止中", value: :false %>
              </td>
            </tr>
          </tbody>
        </table>

        <div class="text-right">
          <%= f.submit '変更を保存', class: "btn btn-primary text-right" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="col-xs-10 col-xs-offset-1">
  <h2>商品一覧</h2>

    <div class="text-right">
      <%= link_to new_admin_item_path do %>
        <button type="button" class="btn btn-success btn-success btn-circle btn-lg">＋</button>
      <% end %>
    </div><br>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admin_item_path(item.id) %></td>
            <td><%= item.price.to_s(:delimited, delimiter: ',') %></td>
            <td><%= item.genre.name %></td>
            <td>
              <% if item.is_active == false %>
                販売停止中
              <% else %>
                販売中
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="row">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <div class="col-xs-5">
        <h2>商品新規登録</h2>

        <div class="col-xs-5 col-xs-offset-2">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th><%= f.label :image, "商品画像" %></th>
                <td><%= f.file_field :image, accept: "image/*", class:"item_image" %></td>
              </tr>
              <tr>
                <th>商品名</th>
                <td><%= f.text_field :name, class: "form-control" %></td>
              </tr>
              <tr>
                <th>商品説明</th>
                <td><%= f.text_area :introduction, class: "form-control" %></td>
              </tr>
              <tr>
                <th>ジャンル</th>
                <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
              </tr>
              <tr>
                <th>税抜価格</th>
                <td><%= f.text_field :price %>円</td>
              </tr>
              <tr>
                <th>販売ステータス</th>
                <td>
                  <%= f.radio_button :is_active, :true %>
                  <%= f.label :is_active_true, "販売中", value: :ture %>
                  <%= f.radio_button :is_active, :false %>
                  <%= f.label :is_active_false, "販売停止中", value: :false %>
                </td>
              </tr>
            </tbody>
          </table>
        <div class="text-right">
          <%= f.submit '新規登録', class: "btn btn-primary"%>
        </div>
      </div>
    </div>
    <% end %>
        </div>
      </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2>商品詳細</h2><br>
  <div class="row">
    <div class="col-sm-4">
      <%= attachment_image_tag @item, :image, :fill, 300, 250, fallback: 'no_image.jpg' %>
    </div>

    <!-- 商品登録フォーム -->
    <div class="col-sm-8">
      <table class="table">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price %>)円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active == false %>
                販売停止中
              <% else %>
                販売中
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= button_to "編集する", edit_admin_item_path(@item.id), method: :get, class:"btn btn-primary", style: "margin-left:50%;"%>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
  <h2>注文履歴詳細</h2>
  <table class="table">
    <tbody>
      <tr>
        <th class="col-xs-4">購入者</th>
        <td class="col-xs-8">
          <%= link_to admin_customer_path(@order.customer) do %>
            <%= @order.customer.last_name %>
            <%= @order.customer.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th class="col-xs-4">注文日</th>
        <td class="col-xs-8"><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th class="col-xs-4">配送先</th>
        <td class="col-xs-8"><%= @order.address %></td>
      </tr>
      <tr>
        <th class="col-xs-4">支払方法</th>
        <td class="col-xs-8"><%= @order.payment_i18n %></td>
      </tr>
      <tr>
        <th class="col-xs-4">注文ステータス</th>
        <td class="col-xs-8">
        <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
          <%= f.select :status, Order.statuses.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="col-xs-8">
    <table class="table">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= (order_detail.price * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
          <td><%= order_detail.amount %></td>
          <td><%= (order_detail.price * 1.1 * order_detail.amount).floor.to_s(:delimited, delimiter: ',') %></td>
          <td>
            <%= form_with model: order_detail, url:admin_order_detail_path(order_detail), local: true do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
              <%= f.submit '更新',class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <br><br><br><br><br><br><br><br><br><br>

  <div class="col-xs-4">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td>商品合計</td>
          <td><%= (@order.total).to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <td>請求合計金額</td>
          <td><%= (@order.total + @order.postage).to_s(:delimited, delimiter: ',') %></td>
        </tr>
      </tbody>
    </table>
   </div>
  </div>
</div>