config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
      resources :order_details, only: [:update]
  end

  scope module: :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw", as: "withdraw"
    get "/customers/edit" => "customers#edit", as: "edit"
    resources :customers, only: [:update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "/orders/confirm" => "orders#confirm"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
   # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postal_code, length: {is: 7}, presence: true
  validates :address, :name, presence: true

	# 配送先住所情報の結合
	def address_display
	    self.postal_code + " " + self.address + " " + self.name
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # 会員フルネーム
  def full_name
    self.last_name + " " + self.first_name
  end
  # 会員フルネーム カナ
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted === false)
  end

  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code,  presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  scope :active, -> {where(is_active: true)}

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  attachment :image
  validates :is_active, inclusion: { in: [true, false] }

  scope :active, -> {where(is_active: true)}

  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  # 注文モデル
  enum payment: { credit_card: 0, transfer: 1 }

  # enumで管理, {0: 入金待ち, 1: 入金確認, 2: 製作中, 3: 発送準備中, 4: 発送済み}
  enum status: { wating: 0, paid_up: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  # enumuで管理, {0: 着手不可, 1:製作待ち, 2: 製作中, 3: 制作完了}
  enum making_status: { no_making: 0, wating: 1, making: 2, finished: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)

  end

  private
	def order_params
		params.require(:order).permit(:status, )
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
    <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container">
          <div class="small text-center text-muted" style="margin: 50px 0;">
            Copyright © 2022  enomo
          </div>
        </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand p-3" href="/"><%= image_tag('logo.jpg') %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>

        <!--顧客がログインしている時 -->
        <li class="nav-item">
          <%= link_to "  マイページ", customers_my_page_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  商品一覧", items_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  カート", cart_items_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  About", about_path, class:'nav-link text-dark' %>
          </li>
        <li class="nav-item">
          <%= link_to "  ログアウト", destroy_customer_session_path, method: :delete, class:'nav-link text-dark' %>
        </li>

      <% elsif admin_signed_in? %>

        <!-- 管理者がログイン時 -->
        <li class="nav-item">
          <%= link_to "  商品一覧", admin_items_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  会員一覧", admin_customers_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  注文履歴一覧", admin_root_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  ジャンル一覧", admin_genres_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link text-dark' %>
        </li>

      <% else %>

        <!-- ログインしていない時 -->
        <li class="nav-item">
          <%= link_to "  About", about_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  商品一覧", items_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  新規登録", new_customer_registration_path, class:'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "  ログイン", new_customer_session_path, class:'nav-link text-dark' %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if customer_signed_in? %>
    <body id="wrapper" style="background-color: white; font-family: HiraMinPro-W6; color: #000000;">
    <!-- header  -->
      <header>
        <%= render "layouts/header" %>
      </header>
    <!-- body -->
      <div class="container" style="margin-top: 20px;">
        <%= yield %>
      </div>
    <!-- footer  -->
    <%= render "layouts/footer" %>
    </body>

  <% elsif admin_signed_in? %>
    <body id="wrapper" style="background-color: #EEEEEE; font-family: HiraMinPro-W6; color: #000000;">
    <!-- header -->
    <header>
      <%= render "layouts/header" %>
    </header>
    <!-- body -->
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
    </div>
    <!-- Footer -->
    <%= render "layouts/footer" %>
    </body>

  <% else %>
    <body id="wrapper" style="background-color: white; font-family: HiraMinPro-W6; color: #000000; ">
    <!-- header -->
    <header>
      <%= render "layouts/header" %>
    </header>
    <!-- body -->
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
    </div>
    <!-- footer -->
    <%= render "layouts/footer" %>
    </body>
  <% end %>
</html>